### ISSUE TITLE
Misconfigured Embed

### ISSUE THREAD

**Issue by gexger** [martink635/twitchls#27]
Site does not work (for me) as of 12/07/20.

Error reads: Whoops! This embed is misconfigured

(Developers: Please check your browser console for more information)

I'm not sure if this is an issue just for me as i cant seem to find any other twitchls users.
I hate the insane amount of shit the main website nonstop throws at you, and i love the simplicity of twitchls. I'd love anything you could do.
I have no experience on github, this seemed to be the only place i could send a message, so if there's anymore information you require i will do my best to find it.

Thanks in advance.

**Comment by Deph0** [comment]
Twitch changed their embed code, as of June 10th. (ref. \[[1]\], \[[2]\])
I've seen other pages with this error as well.

Should be fairly easy to fix for the author of the webpage :) 
I hope it will be a speedy fix and deploy, since i too like the website's minimalism.

[1]: https://discuss.dev.twitch.tv/t/twitch-embedded-player-updates-in-2020/23956
[2]: https://discuss.dev.twitch.tv/t/twitch-embedded-player-migration-timeline-update/25588

**Comment by martink635** [comment]
Thanks for the report, will fix it today 🙂

**Comment by martink635** [comment]
Commit https://github.com/martink635/twitchls/commit/95538050a5f80a87be1262f8b233a57926b325d0 fixes this. Deployed, thanks again for reporting this.

**Comment by gexger** [comment]
Thank you!
