### ISSUE TITLE
Vue.js Devtools chrome extension breaks website

### ISSUE THREAD

**Issue by skcorroh** [martink635/twitchls#34]
When attempting to access https://twitchls.com/ I get a broken page and a single error in the dev console. 
Worked in incognito so I tried disabling all extensions and found that the Vue.js devtools is the culprit. If I change site access from "on all sites" to "on click" the page will load. After clicking the extension it tells me to reload and breaks the site again.

Browser: Microsoft Edge Chromium v.86.0.622.69
Extension: Vue.js Devtools v5.3.3
OS: Windows 10

![image](https://user-images.githubusercontent.com/21206433/100150724-4f2b3500-2e5d-11eb-96e1-76fbe857878d.png)

**Comment by martink635** [comment]
Hey, thanks for the report.

This is sadly due to the dev tools extension not being compatible with vuex 1.x
More information here: https://github.com/vuejs/vue-devtools/issues/916

This is already "fixed" and not a problem in the latest version available at http://next.twitchls.com
It should be moved to the main site soon, as I test it out a bit more and iron out any bugs that come up

**Comment by skcorroh** [comment]
@martink635 Learn something new every day :) wasn't sure if it was an issue (and I know the general user won't have the extension so it wouldn't be a problem) happened to find it and thought I'd let you know.

I'll take a look at the latest version!

**Comment by subin7** [comment]
@skcorroh Thanks.. I had the same problem and it had been bugging me for a while
